[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = ['haskell']

[[plugins]]
repo = 'okue/hasksyn'
on_ft = ['haskell']

[[plugins]]
repo = 'okue/vim-haskellConcealPlus'
on_ft = ['haskell']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
