[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'elmcast/elm-vim'
on_ft = ['elm']
hook_add = '''
let g:elm_setup_keybindings = 0
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
on_i = 1
hook_add = '''
set hidden
let g:LanguageClient_diagnosticsEnable = 0
let g:LanguageClient_rootMakers = {
    \ 'haskell': ['*.cabal', 'stack.yaml'],
    \ } 
let g:LanguageClient_serverCommands = {
    \ 'haskell': [ 'hie-wrapper' ],
    \ 'c'      : [ 'clangd' ],
    \ 'cpp'    : [ 'clangd' ],
    \ 'python' : [ 'pyls' ],
    \ 'ruby'   : [ 'solargraph', 'stdio' ],
    \ 'kotlin' : [ '~/dotfiles/KotlinLanguageServer/server/build/install/server/bin/server' ],
    \ }
'''
